#!/usr/bin/env python3
"""Generate a SCION topology XML from the BGP scenario program's own link table.

Every BGP-vs-SCION comparison in this project depends on both simulators running the same
graph, and every mismatch found so far came from the two descriptions being maintained by hand
in different files and drifting apart: the ``dual`` family ran BGP on a 29-link split topology
against a 21-link SCION XML, and the ``single`` family ran BGP on 13 links against SCION's 12,
handing BGP two paths that bypassed the IXP entirely.

Transcribing by hand is what caused that, so this script does not transcribe. It reads the CSV
written by ``bgp-ixp-scenarios --dumpTopology`` and emits the XML from it, which makes the two
descriptions agree by construction rather than by review. Link order is preserved because both
simulators assign interface indices in declaration order, so a reordered XML resolves interface
IDs differently even when the edge multiset matches.

Usage::

    ./build/scratch/bgp-ixp-scenarios --dualIxp=1 --splitEdgeAs=1 --splitFabricPerIxp=1 \\
        --simTime=60 --dumpTopology=/tmp/topo.csv
    python3 utils/bgp_topology_to_scion_xml.py /tmp/topo.csv \\
        topology/ixp_split_fabric_topology.xml --comment "..."
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List, Tuple

# SCION needs every AS declared before the links. AS101 must come first: the ScionCoreAs
# constructor gives alias 0 special handling, and every existing topology in this repo puts 101
# there.
FIRST_AS = "101"


def read_links(dump_csv: Path) -> List[Dict[str, str]]:
    """Read the link table emitted by ``--dumpTopology``, preserving declaration order."""
    with dump_csv.open() as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise SystemExit(f"{dump_csv} contains no links")
    return rows


def ordered_ases(links: List[Dict[str, str]]) -> List[str]:
    """AS ids in first-appearance order, with AS101 forced to the front."""
    seen: List[str] = []
    for row in links:
        for key in ("as_a", "as_b"):
            asn = row[key].strip()
            if asn not in seen:
                seen.append(asn)
    if FIRST_AS in seen:
        seen.remove(FIRST_AS)
        seen.insert(0, FIRST_AS)
    return seen


def xml_comment_safe(text: str) -> str:
    """Make text legal inside an XML comment, where a double hyphen is not allowed."""
    return text.replace("--", "- -")


def render(links: List[Dict[str, str]], comment: str) -> str:
    """Render the full topology XML."""
    out: List[str] = ['<?xml version="1.0" encoding="UTF-8"?>']
    out.append("<!--")
    for line in xml_comment_safe(comment.strip()).splitlines():
        out.append(f"  {line}".rstrip())
    out.append("")
    out.append("  GENERATED by utils/bgp_topology_to_scion_xml.py from the link table written")
    out.append("  by the BGP scenario program's dumpTopology flag. Do not edit by hand:")
    out.append("  regenerate it, so the BGP and SCION graphs cannot drift apart.")
    out.append("-->")
    out.append("<topology>")
    out.append("  <ases>")
    for asn in ordered_ases(links):
        out.append(f'    <as id="{asn}">')
        out.append('      <property name="isd" value="1"/>')
        out.append('      <property name="type" value="core"/>')
        out.append("      <hosts>")
        # One host per AS. A second host is not usable: pre-simulation-setup.cc looks up the
        # per-AS probe-host cap by alias index against a map keyed by the real XML id, so the
        # keys never intersect and only host 2 is ever created.
        out.append('        <host id="2"/>')
        out.append("      </hosts>")
        out.append("    </as>")
    out.append("  </ases>")
    out.append("")

    for row in links:
        latency = float(row["latency_s"])
        out.append("  <link>")
        out.append(f"    <from>{row['as_a']}</from>")
        out.append(f"    <to>{row['as_b']}</to>")
        out.append(
            f'    <property name="capacity" type="int">{row["capacity_mbps"]}</property>'
        )
        out.append('    <property name="rel" type="string">core</property>')
        out.append('    <property name="latitude" type="float">0.0</property>')
        out.append('    <property name="longitude" type="float">0.0</property>')
        out.append(f'    <property name="latency" type="float">{latency:.4f}</property>')
        out.append(
            f'    <property name="from_if_id" type="int">{row["if_id_a"]}</property>'
        )
        out.append(f'    <property name="to_if_id" type="int">{row["if_id_b"]}</property>')
        out.append("  </link>")

    out.append("</topology>")
    return "\n".join(out) + "\n"


def verify(xml_path: Path, links: List[Dict[str, str]]) -> Tuple[bool, str]:
    """Re-parse the written XML and confirm it round-trips to the same ordered link table."""
    import xml.etree.ElementTree as ET

    root = ET.parse(xml_path).getroot()
    parsed = []
    for link in root.findall(".//link"):
        props = {p.get("name"): p.text.strip() for p in link.findall("property")}
        parsed.append(
            (
                link.find("from").text.strip(),
                link.find("to").text.strip(),
                f"{float(props['latency']):.4f}",
                props["capacity"],
                props["from_if_id"],
                props["to_if_id"],
            )
        )
    expected = [
        (
            r["as_a"],
            r["as_b"],
            f"{float(r['latency_s']):.4f}",
            r["capacity_mbps"],
            r["if_id_a"],
            r["if_id_b"],
        )
        for r in links
    ]
    if parsed == expected:
        return True, f"OK: {len(parsed)} links round-trip identically"
    for i, (got, want) in enumerate(zip(parsed, expected)):
        if got != want:
            return False, f"row {i} differs: xml={got} dump={want}"
    return False, f"length differs: xml={len(parsed)} dump={len(expected)}"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("dump_csv", type=Path, help="CSV from --dumpTopology")
    parser.add_argument("xml_out", type=Path, help="SCION topology XML to write")
    parser.add_argument(
        "--comment", default="SCION counterpart of a BGP scenario topology.",
        help="Header comment describing the scenario",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    links = read_links(args.dump_csv)
    args.xml_out.write_text(render(links, args.comment))
    ok, message = verify(args.xml_out, links)
    print(f"{args.xml_out}: {message}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
